name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup
      run: sudo apt-get update

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libasound2-dev pkg-config
  
    - uses: actions/checkout@v4
    
    - name: Build
      run: cargo build --verbose
      
