name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup
      run: sudo apt-get update

    - uses: actions/checkout@v4
    
    - name: Build
      run: cargo build --verbose
